- name: Install Docker repository [Key]
  ansible.builtin.apt_key:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    state: present
    keyring: /etc/apt/trusted.gpg.d/docker.gpg

- name: Install Docker repository
  ansible.builtin.apt_repository:
    repo: >
      deb [signed-by=/etc/apt/trusted.gpg.d/docker.gpg] 
      https://download.docker.com/linux/{{  ansible_distribution | lower }}
      {{ ansible_distribution_release }} stable
    state: present
    filename: docker-ce-stable

- name: Install containerd
  ansible.builtin.apt:
    name: containerd
    state: present

- name: Create containerd directory
  ansible.builtin.file:
    path: /etc/containerd
    state: directory
    mode: u=rw,g=r,o=r

- name: Create containerd config.toml
  ansible.builtin.shell: containerd config default > /etc/containerd/config.toml

- name: Add cgroup v2 [config.toml]
  ansible.builtin.shell: |
    sed -i 's|SystemdCgroup = false|SystemdCgroup = true|' /etc/containerd/config.toml

- name: Enable and start Containerd service
  ansible.builtin.systemd_service:
    name: containerd
    state: restarted
    enabled: true
