- name: Install K8S repository[key]
  ansible.builtin.apt_key:
    url: "https://pkgs.k8s.io/core:/stable:/v{{ kube_version | regex_search('[0-9]+.[0-9]+') }}/deb/Release.key"
    state: present
    keyring: /etc/apt/trusted.gpg.d/k8s.gpg

- name: Install K8S repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/trusted.gpg.d/k8s.gpg] https://pkgs.k8s.io/core:/stable:/v{{ kube_version | regex_search('[0-9]+.[0-9]+') }}/deb/ /"
    state: present
    filename: kubernetes

- name: Install k8s utils
  ansible.builtin.apt:
    pkg:
      - kubectl
      - kubelet
      - kubeadm
    state: present
