---
- name: update cache
  ansible.builtin.apt:
    update_cache: true

- name: install applications
  ansible.builtin.apt:
    pkg:
    - net-tools
    - mc
    - gpg
    - iproute2
    - iptables
    - vim
    - git
    - bash-completion
    - nfs-common
    - tar
    - ntp
    - jq
    - ipvsadm
    state: present 

- name: Stop UFW unit
  ansible.builtin.systemd_service:
    name: ufw
    state: stopped
    enabled: false

- name: Disable apparmor unit
  ansible.builtin.systemd_service:
    name: apparmor
    state: stopped
    enabled: false

- name: Start and enable ntpd
  ansible.builtin.systemd_service:
    name: ntpd
    state: started
    enabled: true

- name: Test swap
  ansible.builtin.shell: "swapon --show --noheadings | wc -l"
  register: swap_ret

- name: If swap is enabled - disable it
  ansible.builtin.command: swapoff -a
  when: swap_ret.stdout != "0"

- name: Disable SWAP in fstab
  when: swap_ret.stdout != "0"
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '^([^#].*\s*swap\s*.*)$'
    replace: '# \1'

- name: Load modules br_netfilter
  community.general.modprobe:
    name: br_netfilter

- name: Load modules overlay
  community.general.modprobe:
    name: overlay

- name: Load module permanet
  ansible.builtin.copy:
    src: modules-kubernetes.conf
    dest: /etc/modules-load.d/modules-kubernetes.conf
    owner: root
    mode: u=rw,g=r,o=r

- name: Set Sysctl on all nodes
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  with_items:
    - name: net.ipv4.ip_forward
      value: 1
    - name: net.bridge.bridge-nf-call-iptables
      value: 1
    - name: net.bridge.bridge-nf-call-ip6tables
      value: 1
    - name: vm.max_map_count # for opensearch & elasticserarch
      value: 262144

- name: Create crictl config.yaml
  ansible.builtin.template:
    src: crictl.j2
    dest: /etc/crictl.yaml
    owner: root
    mode: u=rw,g=r,o=r

- name: Install containerd
  ansible.builtin.include_tasks: containerd.yaml

- name: Change containerd sock file rights
  ansible.builtin.file:
    path: /var/run/containerd/containerd.sock
    mode: u=rw,g=rw,o=rw

- name: Install crictl
  ansible.builtin.include_tasks: crictl.yaml

- name: Install Kube
  ansible.builtin.include_tasks: kube.yaml
